"""empty message

Revision ID: 3e2f4080e6f1
Revises: None
Create Date: 2016-05-14 11:53:43.092443

"""

# revision identifiers, used by Alembic.
revision = '3e2f4080e6f1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=228), nullable=True),
    sa.Column('city', sa.String(length=228), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal', sa.String(length=50), nullable=True),
    sa.Column('accommodations', sa.String(length=228), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('attending', sa.Boolean(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    op.drop_table('party')
    ### end Alembic commands ###
